---
collections:
  - name: community.hashi_vault
  - name: community.general

roles:
  - src: "git+https://github.com/eclipse-slm/slm-ansible-role-inventory-helper"
    scm: git
    version: 1.0.1
    name: inventory_helper